sudo: required
dist: xenial

language: python

env:
    global:
        - TEST_RUN_FOLDER="/tmp"

cache:
    apt: true
    directories:
        - $HOME/.cache/pip
        - $HOME/.ccache
jobs:
    include:

        - python: 3.9
          os: linux
          arch: amd64
          env:
              - FLAKE8=true

        - python: 3.9
          os: linux
          arch: arm64
          if: commit_message =~ /\[arm64\]/
          env:
              - CPU_COUNT=4

        - python: 3.8
          os: linux
          arch: arm64
          if: type = cron or commit_message =~ /\[cd build\]/
          env:
              - BUILD_WHEEL=true
              - CIBW_BUILD=cp38-manylinux_aarch64

        - python: 3.9
          os: linux
          arch: arm64
          if: type = cron or commit_message =~ /\[cd build\]/
          env:
              - BUILD_WHEEL=true
              - CIBW_BUILD=cp39-manylinux_aarch64

install: source tools/travis/install.sh
script: source tools/travis/test_script.sh
after_success: source tools/travis/after_success.sh
