sudo: required
dist: xenial

language: python

env:
    global:
        - TEST_RUN_FOLDER="/tmp"

matrix:
    fast_finish: true
    allow_failures:
        - python: "3.8"
          env: DISTRIB="travisci" PIP_FLAGS="--pre" COVERAGE="true"
    include:
        - name: "Python 3.7 latest package versions"
          python: "3.7"
          env: DISTRIB="travisci" PYTHON_VERSION="3.7" COVERAGE="true" MATPLOTLIB_VERSION="*"

install: source continuous_integration/install.sh

#before_script: make clean

script: source continuous_integration/test_script.sh

after_success: source continuous_integration/after_success.sh
