name: toy_pkg
channels:
    - conda-forge
dependencies:
    - pip
    - numpy
    - scipy
    - matplotlib==3.3.3
    - pandas
    - scikit-learn
    - jupyter
    - joblib
    - pytest==6.1.2
    - pytest-cov
