name: toy_pkg
channels:
    - conda-forge
dependencies:
    - pip
    - numpy==1.11
    - scipy==0.19
    - pandas==0.23.0
    - scikit-learn==0.19
    - joblib==0.12
    - pytest==6.1.0
    - pytest-cov
    - lxml
    - codecov
