# Python CircleCI 2.0 configuration file
version: 2
jobs:
    build_docs:
        docker:
            - image: circleci/python:3.8.5-buster

        steps:
            - restore_cache:
                keys:
                    - source-cache
            - checkout
            - run:
                name: Complete checkout
                command: |
                    if ! git remote -v | grep upstream; then
                        git remote add upstream git://github.com/NicolasGensollen/toy_pkg.git
                    fi
                    git fetch upstream
            - save_cache:
                key: source-cache
                paths:
                    - ".git"
            - run:
                name: Merge with upstream
                command: |
                    echo $(git log -1 --pretty=%B) | tee gitlog.txt
                    echo ${CI_PULL_REQUEST//*pull\//} | tee merge.txt
                    if [[ $(cat merge.txt) != "" ]]; then
                        echo "Merging $(cat merge.txt)";
                        git pull --ff-only upstream "refs/pull/$(cat merge.txt)/merge";
                    fi
            # Load pip cache
            - restore_cache:
                keys:
                  - pip-cache
            - run:
                name: Get Python running
                command: |
                  ./tools/circleci_dependencies.sh
            - save_cache:
                key: pip-cache
                paths:
                  - ~/.cache/pip
            - save_cache:
                key: user-install-bin-cache
                paths:
                  - ~/.local/lib/python3.8/site-packages
                  - ~/.local/bin
            - run:
                name: Get data
                command: |
                    ./tools/circleci_download.sh
            - run:
                name: Verify build type
                command: |
                    echo "PATTERN=$(cat pattern.txt)"
                    echo "BUILD=$(cat build.txt)"
            # Build docs
            - run:
                name: make html
                command: |
                    cd doc;
                    PATTERN=$(cat ../pattern.txt) make $(cat ../build.txt);
            - store_artifacts:
                path: doc/build/test-results
                destination: test-results
            # Save the HTML
            - store_artifacts:
                path: doc/build/html/
                destination: dev
            - store_artifacts:
                path: doc/build/html_stable/
                destination: stable
            - persist_to_workspace:
                root: doc/build
                paths:
                  - html
                  - html_stable

workflows:
    version: 2

    default:
        jobs:
            - build_docs
