name: 'linux / conda'
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  check_skip:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.result_step.outputs.ci-skip }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: result_step
        uses: mstachniuk/ci-skip@master
        with:
          commit-filter: '[skip ci];[ci skip];[skip github]'
          commit-filter-separator: ';'

  # Linux
  job:
    needs: check_skip
    if: ${{ needs.check_skip.outputs.skip == 'false' }}
    runs-on: ubuntu-latest
    strategy:
        matrix:
            python-version: [3.5, 3.6, 3.7, 3.8]
    name: Python ${{ matrix.python-version }}
    defaults:
      run:
        shell: bash
    env:
      CONDA_ENV: environment.yml
      CONDA_DEPENDENCIES: 'numpy scipy matplotlib'
      DISPLAY: ':99.0'
      MNE_LOGGING_LEVEL: 'warning'
      MKL_NUM_THREADS: '1'
      PYTHONUNBUFFERED: '1'
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: toy_pkg
          python-version: ${{ matrix.python_version }}
          environment-file: ${{ env.CONDA_ENV }}
        name: 'Setup conda'
      - shell: bash -el {0}
        run: ./tools/github_actions_dependencies.sh
        name: 'Install dependencies'
      - shell: bash -el {0}
        run: ./tools/github_actions_install.sh
        name: 'Install toy_pkg'
      - shell: bash -el {0}
        run: ./tools/github_actions_test.sh
        name: 'Run tests'
      - uses: codecov/codecov-action@v1
        if: success()
        name: 'Upload coverage to CodeCov'
