name: 'test'

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.7"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - shell: bash {0}
        name: 'Display Python version'
        run: python --version
      - shell: bash {0}
        run: ln -s ${{ env.pythonLocation }} python
        name: 'ugly'
      - shell: bash {0}
        name: 'Display Python version2'
        run: python --version
      - shell: bash {0}
        name: 'which python'
        run: |
            which python
            which pip
      - shell: bash {0}
        run: ./tools/github_actions_dependencies.sh
        name: 'Install dependencies'
      - shell: bash {0}
        run: ./tools/github_actions_install.sh
        name: 'Install toy_pkg'
      - shell: bash {0}
        run: ./tools/github_actions_test.sh
        name: 'Run tests'
     

